- name: create /usr/share/elasticsearch/data folder
  file:
    path: /usr/share/elasticsearch/data
    state: directory
    mode: 0777
    setype: svirt_sandbox_file_t

- name: call docker service ls elasticsearch-master
  command: docker service ls
  register: docker_service_ls_elasticsearch_master

- name: exec elasticsearch-master
  command: docker service create --name elasticsearch-master -p 9200:9200 -p 9300:9300 --env cluster.name=docker-cluster --env node.master=true --env node.data=false docker.elastic.co/elasticsearch/elasticsearch:6.1.2
  when: "'elasticsearch-master' not in docker_service_ls_elasticsearch_master.stdout"


