---
- name: Install server
  hosts: server
  remote_user: root

  roles:
    - sysctl
    - docker
    - docker-swarm
    - docker-swarm-nginx
    - docker-swarm-jenkins
    - jenkins-job-builder
    - docker-swarm-filebeat
    - docker-swarm-logstash
    - docker-swarm-elasticsearch
