---
- name: call docker service ls kibana
  command: docker service ls
  register: docker_service_ls_kibana

- name: exec kibana
  command: docker service create --name kibana --env ELASTICSEARCH_URL=http://elasticsearch-master:9200 --network elk_overlay_network -p 5601:5601 docker.elastic.co/kibana/kibana:6.1.2
  when: "'kibana' not in docker_service_ls_logstash.stdout"
