---
- name: Add docker repository
  yum_repository:
    name: docker
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
    gpgcheck: 1
    enabled: 1
    gpgkey: https://yum.dockerproject.org/gpg

- name: Install docker packages
  yum: name={{ item }} state=present
  with_items:
   - docker-engine
   - docker-engine-selinux

- name: Start Docker Service
  service: name=docker state=started enabled=yes

